language: python
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=django111
  - DJANGO_VERSION=djangomaster
install: pip install tox-travis
script: tox -e $DJANGO_VERSION

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  on:
#    branch: master
#  local_dir: stats
